In [6]:
#Så nu börjar vi, läs in datafanet
#Vänta, de snackar inte svenksa
#Hello ALL, I promise to code in this new funky language called english

In [11]:
#Import all of the libs
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seabird
import netCDF4

In [12]:
#Ethan gave me pycnv, lets use that
import pycnv

In [9]:
#Open the god damn CNV


#from seabird.cnv import fCNV

#data_2019_1 = fCNV('data/2019/Station1.cnv')
#data_2019_1.keys()

#Get all of the data
#data_2019_2 = fCNV('data/2019/Station2.cnv')
#data_2019_3 = fCNV('data/2019/Station3.cnv')
#data_2019_4 = fCNV('data/2019/Station4.cnv')
#data_2019_5 = fCNV('data/2019/Station5.cnv')
#data_2019_6 = fCNV('data/2019/Station6.cnv')

In [10]:
#Testa att plotta fanskapet
plt.plot(data_2019_1['flECO-AFL'], data_2019_1['DEPTH'], label="Station 1")
plt.plot(data_2019_2['flECO-AFL'], data_2019_2['DEPTH'], label="Station 2")
plt.plot(data_2019_3['flECO-AFL'], data_2019_3['DEPTH'], label="Station 3")
plt.plot(data_2019_4['flECO-AFL'], data_2019_4['DEPTH'], label="Station 4")
plt.plot(data_2019_5['flECO-AFL'], data_2019_5['DEPTH'], label="Station 5")
plt.plot(data_2019_6['flECO-AFL'], data_2019_6['DEPTH'], label="Station 6")
plt.gca().invert_yaxis()
plt.legend()
plt.title("2019", fontweight="bold")
plt.show()

NameError: name 'data_2019_1' is not defined

In [ ]:
#Use Ethies code
st_1_19 = pycnv.pycnv('data/2019/Station1.cnv')
st_2_19 = pycnv.pycnv('data/2019/Station2.cnv')
st_3_19 = pycnv.pycnv('data/2019/Station3.cnv')
st_4_19 = pycnv.pycnv('data/2019/Station4.cnv')
st_5_19 = pycnv.pycnv('data/2019/Station5.cnv')
st_6_19 = pycnv.pycnv('data/2019/Station6.cnv')

 Opening file: data/2019/Station1.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2019/Station2.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2019/Station3.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2019/Station4.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2019/Station5.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2019/Station6.cnv
Converting conductivity units from S/m to mS/cm

In [ ]:
#test this data
data_1 = st_2_19.data
data_1["depSM"]
#Nice

array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
       11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5,
       17. ])

In [ ]:
#Use ethans code to mush it all together
df_2019 = pd.DataFrame()

# List of all your pycnv objects and an identifier for each
stations = [
    (st_1_19, 'ST_1'),
    (st_2_19, 'ST_2'),
    (st_3_19, 'ST_3'),
    (st_4_19, 'ST_4'),
    (st_5_19, 'ST_5'),
    (st_6_19, 'ST_6')
]

dfs_to_concat = []  # Create an empty list to store DataFrames

for station, station_name in stations:
    station_df = pd.DataFrame(station.data)
    
    # Add a column to identify the station
    station_df['STATION'] = station_name
    
    # Append the DataFrame to the list
    dfs_to_concat.append(station_df)

# Concatenate all DataFrames in the list
df_2019 = pd.concat(dfs_to_concat, ignore_index=True)

print(df_2019)

# Specify the filename for the Excel file
#file_name = "tue_cruise.xlsx"

# Save the DataFrame to an Excel file
#df_2019.to_csv("data_2019")

     latitude  longitude      timeJ    t090C       T0     c0S/m        C0  \
0    58.33289   11.87168  39.358724  15.2260  15.2260  2.847648  2.847648
1    58.33294   11.87170  39.358961  15.1916  15.1916  2.833230  2.833230
2    58.33294   11.87170  39.358962  15.1439  15.1439  2.803977  2.803977
3    58.33294   11.87170  39.358978  15.5512  15.5512  2.881293  2.881293
4    58.33294   11.87170  39.358992  15.6653  15.6653  2.942498  2.942498
..        ...        ...        ...      ...      ...       ...       ...
304  58.34160   11.89870  39.487248   8.4884   8.4884  3.377418  3.377418
305  58.34160   11.89870  39.487263   8.5363   8.5363  3.384589  3.384589
306  58.34160   11.89870  39.487278   8.5851   8.5851  3.391516  3.391516
307  58.34160   11.89870  39.487294   8.6424   8.6424  3.399803  3.399803
308  58.34160   11.89869  39.487350   8.6080   8.6080  3.380551  3.380551

       prDM       p  sbeox0V    oxy0  dz/dtM  flECO-AFL    upoly0    sal00  \
0     1.009   1.009   2.1382  2.1382   0.039     1.0204  0.984802  22.0810
1     1.514   1.514   2.1524  2.1524   0.325     1.0027  1.018130  21.9775
2     2.019   2.019   2.1590  2.1590   0.331     1.0633  1.031586  21.7535
3     2.523   2.523   2.1532  2.1532   0.371     1.1464  0.997857  22.1834
4     3.028   3.028   2.1736  2.1736   0.398     0.9537  0.947518  22.6392
..      ...     ...      ...     ...     ...        ...       ...      ...
304  23.722  23.722   0.5476  0.5476   0.403     3.5184  2.174302  31.9341
305  24.227  24.227   0.5442  0.5442   0.397     3.3456  2.151250  31.9658
306  24.731  24.731   0.5412  0.5412   0.394     2.8936  1.902374  31.9938
307  25.236  25.236   0.5387  0.5387   0.373     1.9749  1.596626  32.0284
308  25.741  25.741   0.5321  0.5321  -0.119     1.3445  1.363098  31.8580

     sbox0Mm/Kg  depSM  flag STATION
0       224.836    1.0   0.0    ST_1
1       234.072    1.5   0.0    ST_1
2       229.745    2.0   0.0    ST_1
3       223.576    2.5   0.0    ST_1
4       227.864    3.0   0.0    ST_1
..          ...    ...   ...     ...
304       5.255   23.5   0.0    ST_6
305       4.942   24.0   0.0    ST_6
306       4.558   24.5   0.0    ST_6
307       4.378   25.0   0.0    ST_6
308       3.760   25.5   0.0    ST_6

[309 rows x 19 columns]

In [ ]:
#It fucking works, lets go
#just make a csv for every year then

In [ ]:
#Repeat for 2020
st_1_20 = pycnv.pycnv('data/2020/st_A_conv.cnv')
st_2_20 = pycnv.pycnv('data/2020/st_B_conv.cnv')
st_3_20 = pycnv.pycnv('data/2020/st_C_conv.cnv')
st_4_20 = pycnv.pycnv('data/2020/st_D_conv.cnv')
st_5_20 = pycnv.pycnv('data/2020/st_E_conv.cnv')
st_6_20 = pycnv.pycnv('data/2020/st_F_conv.cnv')
st_7_20 = pycnv.pycnv('data/2020/st_G_conv.cnv')
st_8_20 = pycnv.pycnv('data/2020/st_J_conv.cnv')

 Opening file: data/2020/st_A_conv.cnv
Converting conductivity units from S/m to mS/cm
/home/filip/.local/lib/python3.11/site-packages/gsw/stability.py:86: RuntimeWarning: divide by zero encountered in divide
  N2 = ((g_local**2) / (specvol_mid * db_to_pa * dp))
/home/filip/.local/lib/python3.11/site-packages/gsw/stability.py:87: RuntimeWarning: invalid value encountered in multiply
  N2 *= (beta_mid*dSA - alpha_mid*dCT)
 Opening file: data/2020/st_B_conv.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2020/st_C_conv.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2020/st_D_conv.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2020/st_E_conv.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2020/st_F_conv.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2020/st_G_conv.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2020/st_J_conv.cnv
Converting conductivity units from S/m to mS/cm

In [ ]:
#Now loop that shit

#Use ethans code to mush it all together
df_2020 = pd.DataFrame()

# List of all your pycnv objects and an identifier for each
stations = [
    (st_1_20, 'ST_1'),
    (st_2_20, 'ST_2'),
    (st_3_20, 'ST_3'),
    (st_4_20, 'ST_4'),
    (st_5_20, 'ST_5'),
    (st_6_20, 'ST_6'),
    (st_7_20, 'ST_7'),
    (st_8_20, 'ST_8')
]

dfs_to_concat = []  # Create an empty list to store DataFrames

for station, station_name in stations:
    station_df = pd.DataFrame(station.data)
    
    # Add a column to identify the station
    station_df['STATION'] = station_name
    
    # Append the DataFrame to the list
    dfs_to_concat.append(station_df)

# Concatenate all DataFrames in the list
df_2020 = pd.concat(dfs_to_concat, ignore_index=True)

print(df_2020)
df_2020["Year"] = 2020
df_2020

# Specify the filename for the Excel file
#file_name = "tue_cruise.xlsx"
df_2020

# Save the DataFrame to an Excel file
#df_2020.to_csv("data/2020/data_2020")

       latitude  longitude   prDM      p  depSM    t090C       T0     c0S/m  \
0      58.34232   11.89516  0.829  0.829  0.822  15.3189  15.3189  2.673132
1      58.34232   11.89516  0.893  0.893  0.885  15.3263  15.3263  2.672828
2      58.34232   11.89516  0.893  0.893  0.885  15.3253  15.3253  2.672772
3      58.34232   11.89516  0.829  0.829  0.822  15.3233  15.3233  2.672884
4      58.34232   11.89516  0.893  0.893  0.885  15.3202  15.3202  2.672823
...         ...        ...    ...    ...    ...      ...      ...       ...
88777  58.33848   11.88898 -0.160 -0.160 -0.159  13.4873  13.4873  1.045088
88778  58.33848   11.88898 -0.160 -0.160 -0.159  13.4851  13.4851  1.050196
88779  58.33848   11.88898 -0.224 -0.224 -0.221  13.4848  13.4848  1.046603
88780  58.33848   11.88898 -0.160 -0.160 -0.159  13.4858  13.4858  1.045669
88781  58.33848   11.88898 -0.160 -0.160 -0.159  13.4849  13.4849  1.059606

             C0    sal00  sbeox0ML/L    oxy0  flECO-AFL  density00     svCM  \
0      2.673132  20.5498      6.2978  6.2978     3.5901  1014.8059  1490.97
1      2.672828  20.5433      6.2971  6.2971     3.5779  1014.7998  1490.99
2      2.672772  20.5433      6.2930  6.2930     3.5901  1014.8000  1490.99
3      2.672884  20.5454      6.2928  6.2928     3.5901  1014.8017  1490.98
4      2.672823  20.5464      6.2928  6.2928     3.5901  1014.8034  1490.97
...         ...      ...         ...     ...        ...        ...      ...
88777  1.045088   7.7580      5.4012  5.4012    -0.0240  1005.3055  1469.80
88778  1.050196   7.7994      5.3962  5.3962    -0.0484  1005.3377  1469.84
88779  1.046603   7.7707      5.3928  5.3928    -0.0729  1005.3153  1469.81
88780  1.045669   7.7630      5.3884  5.3884    -0.0851  1005.3096  1469.80
88781  1.059606   7.8748      5.3840  5.3840    -0.0851  1005.3957  1469.93

       flag STATION
0       0.0    ST_1
1       0.0    ST_1
2       0.0    ST_1
3       0.0    ST_1
4       0.0    ST_1
...     ...     ...
88777   0.0    ST_8
88778   0.0    ST_8
88779   0.0    ST_8
88780   0.0    ST_8
88781   0.0    ST_8

[88782 rows x 17 columns]

,latitude,longitude,prDM,p,depSM,t090C,T0,c0S/m,C0,sal00,sbeox0ML/L,oxy0,flECO-AFL,density00,svCM,flag,STATION,Year
0,58.34232,11.89516,0.829,0.829,0.822,15.3189,15.3189,2.673132,2.673132,20.5498,6.2978,6.2978,3.5901,1014.8059,1490.97,0.0,ST_1,2020
1,58.34232,11.89516,0.893,0.893,0.885,15.3263,15.3263,2.672828,2.672828,20.5433,6.2971,6.2971,3.5779,1014.7998,1490.99,0.0,ST_1,2020
2,58.34232,11.89516,0.893,0.893,0.885,15.3253,15.3253,2.672772,2.672772,20.5433,6.2930,6.2930,3.5901,1014.8000,1490.99,0.0,ST_1,2020
3,58.34232,11.89516,0.829,0.829,0.822,15.3233,15.3233,2.672884,2.672884,20.5454,6.2928,6.2928,3.5901,1014.8017,1490.98,0.0,ST_1,2020
4,58.34232,11.89516,0.893,0.893,0.885,15.3202,15.3202,2.672823,2.672823,20.5464,6.2928,6.2928,3.5901,1014.8034,1490.97,0.0,ST_1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88777,58.33848,11.88898,-0.160,-0.160,-0.159,13.4873,13.4873,1.045088,1.045088,7.7580,5.4012,5.4012,-0.0240,1005.3055,1469.80,0.0,ST_8,2020
88778,58.33848,11.88898,-0.160,-0.160,-0.159,13.4851,13.4851,1.050196,1.050196,7.7994,5.3962,5.3962,-0.0484,1005.3377,1469.84,0.0,ST_8,2020
88779,58.33848,11.88898,-0.224,-0.224,-0.221,13.4848,13.4848,1.046603,1.046603,7.7707,5.3928,5.3928,-0.0729,1005.3153,1469.81,0.0,ST_8,2020
88780,58.33848,11.88898,-0.160,-0.160,-0.159,13.4858,13.4858,1.045669,1.045669,7.7630,5.3884,5.3884,-0.0851,1005.3096,1469.80,0.0,ST_8,2020
88781,58.33848,11.88898,-0.160,-0.160,-0.159,13.4849,13.4849,1.059606,1.059606,7.8748,5.3840,5.3840,-0.0851,1005.3957,1469.93,0.0,ST_8,2020

In [ ]:
#Now we do some work to remove the upcasts!
    #Separate by stations first

df_2020_st1= (df_2020.loc[df_2020["STATION"]=='ST_1'])
df_2020_st2 = (df_2020.loc[df_2020['STATION']=='ST_2'])
df_2020_st3 = (df_2020.loc[df_2020['STATION']=='ST_3'])
df_2020_st4 = (df_2020.loc[df_2020['STATION']=='ST_4'])
df_2020_st5 = (df_2020.loc[df_2020['STATION']=='ST_5'])
df_2020_st6 = (df_2020.loc[df_2020['STATION']=='ST_6'])
df_2020_st7 = (df_2020.loc[df_2020['STATION']=='ST_7'])
df_2020_st8 = (df_2020.loc[df_2020['STATION']=='ST_8'])


#Now we find the max index for each depth and select all those rows before that.
df_2020_st1[['depSM']].idxmax()
df_2020_st1_trim = df_2020_st1.iloc[0:3401,]
df_2020_st2[['depSM']].idxmax()
    #23734
    #23734 - 21141
df_2020_st2_trim = df_2020_st2.iloc[0:2594,]

df_2020_st3[['depSM']].idxmax() #40006
#40006 - 32402
df_2020_st3_trim = df_2020_st3.iloc[0:7605,]

df_2020_st4[['depSM']].idxmax() #47273
#47273 - 44725
df_2020_st4_trim = df_2020_st4.iloc[0:2549,]

df_2020_st5[['depSM']].idxmax() #61441
#61441 - 55759
df_2020_st5_trim = df_2020_st5.iloc[0:5683,]

df_2020_st6[['depSM']].idxmax() #71981
df_2020_st6_trim = df_2020_st6.iloc[0:2224,]

df_2020_st7[['depSM']].idxmax() #81583
df_2020_st7_trim = df_2020_st7.iloc[0:2987,]

df_2020_st8[['depSM']].idxmax() # 86840

df_2020_st8_trim = df_2020_st8.iloc[0:3420,]


#Now add these dataframes together.
frames = [df_2020_st1_trim, df_2020_st2_trim, df_2020_st3_trim,df_2020_st4_trim,df_2020_st5_trim,df_2020_st6_trim,df_2020_st7_trim,df_2020_st8_trim]

df_2020_trim = pd.concat(frames)

#make it into csv
#df_2020_trim.to_csv("data/2020/data_2020_trim")

In [ ]:
#Do 2022
    #2021 is funky, do that one later

st_B1_1_22 = pycnv.pycnv('data/2022/thursday_data/Station B1,1.cnv')
st_B1_22 = pycnv.pycnv('data/2022/thursday_data/Station B1.cnv')
st_B2_1_22 = pycnv.pycnv('data/2022/thursday_data/Station B2,1.cnv')
st_B2_22 = pycnv.pycnv('data/2022/thursday_data/Station B2.cnv')
st_B3_22 = pycnv.pycnv('data/2022/thursday_data/Station B3.cnv')
st_H1_22 = pycnv.pycnv('data/2022/thursday_data/Station H1.cnv')
st_H2_22 = pycnv.pycnv('data/2022/thursday_data/Station H2.cnv')
st_H3_1_22 = pycnv.pycnv('data/2022/thursday_data/Station H3,1.cnv')
st_H3_22 = pycnv.pycnv('data/2022/thursday_data/Station H3.cnv')
st_SB1_22 = pycnv.pycnv('data/2022/thursday_data/Station SB1.cnv')
st_SB2_22 = pycnv.pycnv('data/2022/thursday_data/Station SB2.cnv')
st_SH1_22 = pycnv.pycnv('data/2022/thursday_data/Station SH1.cnv')
st_SH2_22 = pycnv.pycnv('data/2022/thursday_data/Station SH2.cnv')

#Wednesday
st_1_22 = pycnv.pycnv('data/2022/wednesday_data/Station 1.cnv')
st_2_22 = pycnv.pycnv('data/2022/wednesday_data/Station 2.cnv')
st_3_22 = pycnv.pycnv('data/2022/wednesday_data/Station 3.cnv')
st_4_22 = pycnv.pycnv('data/2022/wednesday_data/Station 4.cnv')
st_5_22 = pycnv.pycnv('data/2022/wednesday_data/Station 5.cnv')
st_6_22 = pycnv.pycnv('data/2022/wednesday_data/Station 6.cnv')
st_7_22 = pycnv.pycnv('data/2022/wednesday_data/Station 7.cnv')
st_8_22 = pycnv.pycnv('data/2022/wednesday_data/Station 8.cnv')
st_9_22 = pycnv.pycnv('data/2022/wednesday_data/Station 9.cnv')

 Opening file: data/2022/thursday_data/Station B1,1.cnv
Converting conductivity units from S/m to mS/cm
/home/filip/.local/lib/python3.11/site-packages/gsw/stability.py:86: RuntimeWarning: divide by zero encountered in divide
  N2 = ((g_local**2) / (specvol_mid * db_to_pa * dp))
 Opening file: data/2022/thursday_data/Station B1.cnv
Converting conductivity units from S/m to mS/cm
/home/filip/.local/lib/python3.11/site-packages/gsw/stability.py:87: RuntimeWarning: invalid value encountered in multiply
  N2 *= (beta_mid*dSA - alpha_mid*dCT)
 Opening file: data/2022/thursday_data/Station B2,1.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station B2.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station B3.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station H1.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station H2.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station H3,1.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station H3.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station SB1.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station SB2.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station SH1.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/thursday_data/Station SH2.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 1.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 2.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 3.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 4.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 5.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 6.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 7.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 8.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2022/wednesday_data/Station 9.cnv
Converting conductivity units from S/m to mS/cm

In [ ]:
##Loop 2022
#Use ethans code to mush it all together
df_2020 = pd.DataFrame()

# List of all your pycnv objects and an identifier for each
stations = [
    (st_B1_1_22, 'ST_B1_1'),
    (st_B1_22, 'ST_B1'),
    (st_B2_1_22, 'ST_B2_1'),
    (st_B2_22, 'ST_B2'),
    (st_B3_22, 'ST_B3'),
    (st_H1_22, 'ST_H1'),
    (st_H2_22, 'ST_H2'),
    (st_H3_1_22, 'ST_H3_1'),
    (st_H3_22, 'ST_H3'),
    (st_SB1_22, 'ST_SB1'),
    (st_SB2_22, 'ST_SB2'),
    (st_SH1_22, 'ST_SH1'),
    (st_SH2_22, 'ST_SH2'),
    (st_1_22, 'ST_1'),
    (st_2_22, 'ST_2'),
    (st_3_22, 'ST_3'),
    (st_4_22, 'ST_4'),
    (st_5_22, 'ST_5'),
    (st_6_22, 'ST_6'),
    (st_7_22, 'ST_7'),
    (st_8_22, 'ST_8'),
    (st_9_22, 'ST_9'),
]

dfs_to_concat = []  # Create an empty list to store DataFrames

for station, station_name in stations:
    station_df = pd.DataFrame(station.data)
    
    # Add a column to identify the station
    station_df['STATION'] = station_name
    
    # Append the DataFrame to the list
    dfs_to_concat.append(station_df)

# Concatenate all DataFrames in the list
df_2022 = pd.concat(dfs_to_concat, ignore_index=True)

df_2022["Year"] = 2022

#Clean up the data a bit
df_2022_r = df_2022.replace(-9.990000e-29, np.nan)
df_2022_r

# Specify the filename for the Excel file
#file_name = "tue_cruise.xlsx"

# Save the DataFrame to an Excel file
#df_2022.to_csv("data/2022/data_2022_r")

,scan,prDM,p,t090C,T0,c0S/m,C0,sbeox0V,oxy0,flECO-AFL,upoly0,xmiss,depSM,sal00,sbeox0ML/L,flag,STATION,Year
0,1.0,1.257,1.257,18.2878,18.2878,3.263051,3.263051,2.7076,2.7076,0.0255,0.099001,84.4829,1.245,23.7810,5.4053,NaN,ST_B1_1,2022
1,2.0,1.258,1.258,18.2889,18.2889,3.263095,3.263095,2.7075,2.7075,0.0255,0.098989,84.4808,1.246,23.7808,5.4049,NaN,ST_B1_1,2022
2,3.0,1.258,1.258,18.2902,18.2902,3.263142,3.263142,2.7074,2.7074,0.0255,0.098976,84.4786,1.246,23.7804,5.4045,NaN,ST_B1_1,2022
3,4.0,1.259,1.259,18.2916,18.2916,3.263192,3.263192,2.7074,2.7074,0.0255,0.098961,84.4765,1.247,23.7800,5.4044,NaN,ST_B1_1,2022
4,5.0,1.261,1.261,18.2930,18.2930,3.263244,3.263244,2.7073,2.7073,0.0255,0.098946,84.4746,1.249,23.7796,5.4040,NaN,ST_B1_1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63642,3014.0,38.875,38.875,NaN,NaN,3.134591,3.134591,NaN,NaN,0.0026,0.101452,91.4379,38.510,NaN,NaN,NaN,ST_9,2022
63643,3015.0,38.875,38.875,NaN,NaN,3.134591,3.134591,NaN,NaN,0.0026,0.101455,91.4344,38.510,NaN,NaN,NaN,ST_9,2022
63644,3016.0,38.875,38.875,NaN,NaN,3.134590,3.134590,NaN,NaN,0.0026,0.101457,91.4325,38.510,NaN,NaN,NaN,ST_9,2022
63645,3017.0,38.875,38.875,NaN,NaN,3.134590,3.134590,NaN,NaN,0.0026,0.101458,91.4317,38.510,NaN,NaN,NaN,ST_9,2022
63646,3018.0,38.875,38.875,NaN,NaN,3.134590,3.134590,NaN,NaN,0.0026,0.101459,91.4315,38.510,NaN,NaN,NaN,ST_9,2022

In [ ]:
#Now we do some work to remove the upcasts!
    #Separate by stations first

df_2022_st1= (df_2022_r.loc[df_2022_r["STATION"]=='ST_1'])
df_2022_st2 = (df_2022_r.loc[df_2022_r['STATION']=='ST_2'])
df_2022_st3 = (df_2022_r.loc[df_2022_r['STATION']=='ST_3'])
df_2022_st4 = (df_2022_r.loc[df_2022_r['STATION']=='ST_4'])
df_2022_st5 = (df_2022_r.loc[df_2022_r['STATION']=='ST_5'])
df_2022_st6 = (df_2022_r.loc[df_2022_r['STATION']=='ST_6'])
df_2022_st7 = (df_2022_r.loc[df_2022_r['STATION']=='ST_7'])
df_2022_st8 = (df_2022_r.loc[df_2022_r['STATION']=='ST_8'])
df_2022_st9 = (df_2022_r.loc[df_2022_r['STATION']=='ST_9'])

#Now calculate and trim all of that shit

In [ ]:
#Now we do 2023 for the wednesday!
st_1_23 = pycnv.pycnv('data/2023/2023_wed/06CTD01.cnv')
st_2_23 = pycnv.pycnv('data/2023/2023_wed/06CTD02.cnv')
st_3_23 = pycnv.pycnv('data/2023/2023_wed/06CTD03.cnv')
st_4_23 = pycnv.pycnv('data/2023/2023_wed/06CTD04.cnv')
st_5_23 = pycnv.pycnv('data/2023/2023_wed/06CTD05.cnv')
st_6_23 = pycnv.pycnv('data/2023/2023_wed/06CTD06.cnv')
st_8_23 = pycnv.pycnv('data/2023/2023_wed/06CTD08.cnv')
st_9_23 = pycnv.pycnv('data/2023/2023_wed/06CTD09.cnv')
st_10_23 = pycnv.pycnv('data/2023/2023_wed/06CTD10.cnv')
st_11_23 = pycnv.pycnv('data/2023/2023_wed/06CTD11.cnv')
st_12_23 = pycnv.pycnv('data/2023/2023_wed/06CTD12.cnv')
st_13_23 = pycnv.pycnv('data/2023/2023_wed/06CTD13.cnv')
st_14_23 = pycnv.pycnv('data/2023/2023_wed/06CTD14.cnv')
st_15_23 = pycnv.pycnv('data/2023/2023_wed/06CTD15.cnv')
st_16_23 = pycnv.pycnv('data/2023/2023_wed/06CTD16.cnv')

 Opening file: data/2023/2023_wed/06CTD01.cnv
Converting conductivity units from S/m to mS/cm
/home/filip/.local/lib/python3.11/site-packages/gsw/stability.py:86: RuntimeWarning: divide by zero encountered in divide
  N2 = ((g_local**2) / (specvol_mid * db_to_pa * dp))
 Opening file: data/2023/2023_wed/06CTD02.cnv
Converting conductivity units from S/m to mS/cm
/home/filip/.local/lib/python3.11/site-packages/gsw/stability.py:87: RuntimeWarning: invalid value encountered in multiply
  N2 *= (beta_mid*dSA - alpha_mid*dCT)
 Opening file: data/2023/2023_wed/06CTD03.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD04.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD05.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD06.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD08.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD09.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD10.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD11.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD12.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD13.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD14.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD15.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: data/2023/2023_wed/06CTD16.cnv
Converting conductivity units from S/m to mS/cm

In [ ]:
##Loop 2023
#Use ethans code to mush it all together
df_2023 = pd.DataFrame()

# List of all your pycnv objects and an identifier for each
stations = [
    (st_1_23, 'ST_1'),
    (st_2_23, 'ST_2'),
    (st_3_23, 'ST_3'),
    (st_4_23, 'ST_4'),
    (st_5_23, 'ST_5'),
    (st_6_23, 'ST_6'),
    (st_8_23, 'ST_8'),
    (st_9_23, 'ST_9'),
    (st_10_23, 'ST_10'),
    (st_11_23, 'ST_11'),
    (st_12_23, 'ST_12'),
    (st_13_23, 'ST_13'),
    (st_14_23, 'ST_14'),
    (st_15_23, 'ST_15'),
    (st_16_23, 'ST_16'),

]

dfs_to_concat = []  # Create an empty list to store DataFrames

for station, station_name in stations:
    station_df = pd.DataFrame(station.data)
    
    # Add a column to identify the station
    station_df['STATION'] = station_name
    
    # Append the DataFrame to the list
    dfs_to_concat.append(station_df)

# Concatenate all DataFrames in the list
df_2023 = pd.concat(dfs_to_concat, ignore_index=True)

df_2023["Year"] = 2023

#df_2023_r = df_2023.replace(-9.990000e-29, np.nan)
#df_2023_r.to_csv("data/2023/data_2023")

In [15]:
#Now we actually give 2021 a shot
    #Start with da maddafakking CNV
        #Switch to the average file
        #tuesday
st_1_21_tue = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 1 210921_ctm_fil_le_der.cnv')
st_2_21_tue = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 2 210921_ctm_fil_le_der.cnv')
st_3_21_tue = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 3 210921_ctm_fil_le_der.cnv')
st_4_21_tue = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 4 210921_ctm_fil_le_der.cnv')
st_5_21_tue = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 5 210921_ctm_fil_le_der.cnv')
st_6_21_tue = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 6 210921_ctm_fil_le_der.cnv')
st_10_21_tue = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 4ex 210921_ctm_fil_le_der.cnv')
#st_11_21_tue = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/code/data/2021/ctd_data_day1/Station 5ex 210921.cnv')


    #Wednesday
st_1_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station1_ctm_fil_le_der.cnv')
st_2_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station2_ctm_fil_le_der.cnv')
st_3_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station3_ctm_fil_le_der.cnv')
st_4_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station4_ctm_fil_le_der.cnv')
st_5_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station5_ctm_fil_le_der.cnv')
st_6_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station6_ctm_fil_le_der.cnv')
st_7_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station7_ctm_fil_le_der.cnv')
st_8_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station8_ctm_fil_le_der.cnv')
st_9_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station9_ctm_fil_le_der.cnv')
st_10_21_wed = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station10_ctm_fil_le_der.cnv')

#thursday
st_1_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station1a_ctm_fil_le_der.cnv')
st_2_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station2B_ctm_fil_le_der.cnv')
st_3_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station3c_ctm_fil_le_der.cnv')
st_4_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station4d_ctm_fil_le_der.cnv')
st_5_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station5e_ctm_fil_le_der.cnv')
st_6_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station6f_ctm_fil_le_der.cnv')
st_7_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station7g_ctm_fil_le_der.cnv')
st_8_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station8H_ctm_fil_le_der.cnv')
st_9_21_thu = pycnv.pycnv('/home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station9i_ctm_fil_le_der.cnv')

 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 1 210921_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 2 210921_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 3 210921_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 4 210921_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 5 210921_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 6 210921_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day1/Station 4ex 210921_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station1_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
/home/filip/.local/lib/python3.11/site-packages/gsw/stability.py:86: RuntimeWarning: divide by zero encountered in divide
  N2 = ((g_local**2) / (specvol_mid * db_to_pa * dp))
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station2_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
/home/filip/.local/lib/python3.11/site-packages/gsw/stability.py:87: RuntimeWarning: invalid value encountered in multiply
  N2 *= (beta_mid*dSA - alpha_mid*dCT)
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station3_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station4_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station5_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station6_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station7_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station8_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station9_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day2/station10_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station1a_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station2B_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station3c_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station4d_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station5e_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station6f_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station7g_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station8H_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm
 Opening file: /home/filip/R/BioLumi/MAR440_2023/data/2021/ctd_data_day3/station9i_ctm_fil_le_der.cnv
Converting conductivity units from S/m to mS/cm

In [16]:
#Now repeat this process for the 2021
    #copy the same code
        #AGAIN SYYYYYYKE

##Loop 2023
#Use ethans code to mush it all together
df_2021 = pd.DataFrame()

# List of all your pycnv objects and an identifier for each
stations = [
    (st_1_21_tue, 'ST_1_tue'),
    (st_2_21_tue, 'ST_2_tue'),
    (st_3_21_tue, 'ST_3_tue'),
   # (st_4_21_tue, 'ST_4_tue'),
   # (st_5_21_tue, 'ST_5_tue'),
   # (st_6_21_tue, 'ST_6_tue'),
    (st_1_21_wed, 'ST_1_wed'),
    (st_2_21_wed, 'ST_2_wed'),
    (st_3_21_wed, 'ST_3_wed'),
   # (st_4_21_wed, 'ST_4_wed'),
   # (st_5_21_wed, 'ST_5_wed'),
   # (st_6_21_wed, 'ST_6_wed'),
   # (st_7_21_wed, 'ST_7_wed'),
   # (st_8_21_wed, 'ST_8_wed'),
    (st_9_21_wed, 'ST_9_wed'),
    (st_10_21_wed, 'ST_10_wed'),
    (st_1_21_thu, 'ST_1_thu'),
    (st_2_21_thu, 'ST_2_thu'),
    (st_3_21_thu, 'ST_3_thu'),
   # (st_4_21_thu, 'ST_4_thu'),
   # (st_5_21_thu, 'ST_5_thu'),
   # (st_6_21_thu, 'ST_6_thu'),
   # (st_7_21_thu, 'ST_7_thu'),
   # (st_8_21_thu, 'ST_8_thu'),
    (st_9_21_thu, 'ST_9_thu'),
    (st_10_21_tue, 'ST_10_tue')
   

  

]

dfs_to_concat = []  # Create an empty list to store DataFrames

for station, station_name in stations:
    station_df = pd.DataFrame(station.data)
    
    # Add a column to identify the station
    station_df['STATION'] = station_name
    
    # Append the DataFrame to the list
    dfs_to_concat.append(station_df)

# Concatenate all DataFrames in the list
df_2021 = pd.concat(dfs_to_concat, ignore_index=True)

df_2021["Year"] = 2021

df_2021_r = df_2021.replace(-9.990000e-29, np.nan)
df_2021.to_csv("/home/filip/R/BioLumi/MAR440_2023/data/2021/data_2021_v2")

In [ ]:
#Put everything in one file
df_2023_w = pd.read_excel("/home/filip/R/BioLumi/MAR440_2023/code/data/2023/Tue_crise_c_new.xlsx")

In [ ]:
#Add years
df_2019["Year"] = 2019
#df_2020_trim
df_2023_w["Year"] = 2023
df_2021

,scan,prDM,p,t090C,T0,t190C,T1,c0S/m,C0,c1S/m,C1,sbeox0V,oxy0,sbeox1V,oxy1,flECO-AFL,upoly0,flag,STATION,Year
0,1.0,0.797,0.797,14.3835,14.3835,14.4000,14.4000,2.811018,2.811018,2.812145,2.812145,2.8510,2.8510,2.7631,2.7631,0.0059,0.206101,0.0,ST_1_tue,2021
1,2.0,0.706,0.706,14.3814,14.3814,14.4027,14.4027,2.811386,2.811386,2.812177,2.812177,2.8510,2.8510,2.7631,2.7631,0.0059,0.206101,0.0,ST_1_tue,2021
2,3.0,0.797,0.797,14.3829,14.3829,14.4127,14.4127,2.811603,2.811603,2.812279,2.812279,2.8510,2.8510,2.7631,2.7631,0.0059,0.206101,0.0,ST_1_tue,2021
3,4.0,0.706,0.706,14.3817,14.3817,14.4332,14.4332,2.811598,2.811598,2.812477,2.812477,2.8523,2.8523,2.7631,2.7631,0.0059,0.206101,0.0,ST_1_tue,2021
4,5.0,0.797,0.797,14.3791,14.3791,14.4445,14.4445,2.811516,2.811516,2.812648,2.812648,2.8523,2.8523,2.7631,2.7631,0.0059,0.206101,0.0,ST_1_tue,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101764,6119.0,43.459,43.459,8.6852,8.6852,8.6950,8.6950,3.414838,3.414838,3.415479,3.415479,0.4711,0.4711,0.5358,0.5358,0.0038,0.116236,0.0,ST_10_tue,2021
101765,6120.0,43.393,43.393,8.6851,8.6851,8.6956,8.6956,3.414827,3.414827,3.415416,3.415416,0.4711,0.4711,0.5358,0.5358,0.0038,0.116236,0.0,ST_10_tue,2021
101766,6121.0,43.450,43.450,8.6849,8.6849,8.6956,8.6956,3.414838,3.414838,3.415358,3.415358,0.4711,0.4711,0.5358,0.5358,0.0040,0.116236,0.0,ST_10_tue,2021
101767,6122.0,43.393,43.393,8.6853,8.6853,8.6948,8.6948,3.414891,3.414891,3.415375,3.415375,0.4699,0.4699,0.5358,0.5358,0.0040,0.115747,0.0,ST_10_tue,2021
101768,6123.0,43.516,43.516,8.6852,8.6852,8.6943,8.6943,3.414908,3.414908,3.415312,3.415312,0.4711,0.4711,0.5358,0.5358,0.0038,0.116236,0.0,ST_10_tue,2021

In [ ]:
#Now concatenate them all
all_frames = [df_2019, df_2020_trim, df_2021, df_2022, df_2023_w, df_2023]
df_all = pd.concat(all_frames)

df_all_r = df_all.replace(-9.990000e-29, np.nan)
df_all_r

#Make a big csv
#df_all_r.to_csv("/home/filip/R/BioLumi/MAR440_2023/code/data/all_data_better.csv")